spring:
  config:
    activate:
      on-profile: prod
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

auth:
  cookie:
    secure: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,mongo,redis
      show-details: never

logging:
  level:
    root: INFO
    com.veyru: INFO
    org.springframework.security: WARN
